### ISSUE TITLE
Need your help!

### ISSUE THREAD

**Issue by braverynew** [hschickdevs/telegram-crypto-alerts#20]
I had error when I'm running your bot. Please help me to fix it.
Here is logs
__main__ : INFO : 2023-05-08 06:42:30,523 : Bot started - use Ctrl+C to stop the bot.
indicators : CRITICAL : 2023-05-08 06:42:31,778 : An error has occurred in the mainloop - restarting in 5 seconds...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Telegram-Crypto-Alerts/bot/indicators.py", line 359, in run
    self.mainloop()
  File "/root/Telegram-Crypto-Alerts/bot/indicators.py", line 320, in mainloop
    r = self.call_api(endpoint=BULK_ENDPOINT, params=query)
  File "/usr/local/lib/python3.9/dist-packages/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
  File "/usr/local/lib/python3.9/dist-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/root/Telegram-Crypto-Alerts/bot/indicators.py", line 287, in call_api
    return requests.post(endpoint, json=params).json()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
telegram_handler : WARNING : 2023-05-08 06:42:32,550 : taapiio_bot started at 2023-05-08 06:42:32.550406 UTC+0
alert_handler : INFO : 2023-05-08 06:42:33,116 : Bot polling for next alert...
^C__main__ : INFO : 2023-05-08 06:42:37,033 : Bot stopped

Thanks

**Comment by braverynew** [comment]
I fixed it. I used proxy --> had this error.
Thanks

**Comment by hschickdevs** [comment]
Glad you got it fixed @braverynew !
